//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjWebCsHoraireScolaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cour
    {
        public int CoursID { get; set; }
        public string Titre { get; set; }
        public string Description { get; set; }
    }
}
