//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjWebCsHoraireScolaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horaire
    {
        public int HoraireID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string HeureDebut { get; set; }
        public string HeureFin { get; set; }
        public Nullable<int> Professeur { get; set; }
        public Nullable<int> Classe { get; set; }
        public string statut { get; set; }
       
    }
}
