//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjWebCsHoraireScolaire.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_a9c67b_horairescolaireEntities : DbContext
    {
        public db_a9c67b_horairescolaireEntities()
            : base("name=db_a9c67b_horairescolaireEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrateur> Administrateurs { get; set; }
        public virtual DbSet<Cour> Cours { get; set; }
        public virtual DbSet<Etudiant> Etudiants { get; set; }
        public virtual DbSet<Horaire> Horaires { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Professeur> Professeurs { get; set; }
    }
}
