//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjWebCsHoraireScolaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int NotesID { get; set; }
        public Nullable<int> Etudiant { get; set; }
        public Nullable<double> Notes { get; set; }
        public Nullable<int> Cours { get; set; }
    }
}
